# Diamond DA40 NG checklist  
  
version: 6.01.15-E  
issued: 2010-04-01  
  
## CHAPTER 3 — EMERGENCY PROCEDURES  
  
### 3.2 Instrument Indications in Prohibited (Red) Range  
  
**3.2.1 Engine Temperature (Coolant > 105 °C)**  
  
**COOL LVL / WATERLEV caution NOT displayed:**  
  
During climb:  
- [ ] Reduce power by 10% or more as required  
- [ ] Increase airspeed by 10 KIAS or more as required  
- [ ] If coolant temperature does not reach green range within 60 seconds, reduce power as far as possible and increase airspeed  
  
During cruise:  
- [ ] Reduce power, or increase airspeed (if necessary by initiating a descent)  
- [ ] Check coolant temperature returns to green range  
  
**COOL LVL / WATERLEV caution DISPLAYED:**  
- [ ] Reduce power  
- [ ] Expect loss of coolant  
  
**3.2.2 Oil Temperature (> 140 °C)**  
  
If oil pressure is OUTSIDE the green range (lower limit):  
- [ ] Reduce power  
- [ ] Expect loss of engine oil  
  
If oil pressure IS within the green range:  
- [ ] Reduce power  
- [ ] Increase airspeed  
  
**3.2.3 Oil Pressure (< 0.9 bar)**  
  
- [ ] Reduce power  
- [ ] Expect loss of oil  
  
**3.2.4 Gearbox Temperature (> 120 °C)**  
  
- [ ] Reduce power  
- [ ] Increase airspeed  
  
**3.2.5 L/R Fuel Temperature (> 60 °C)**  
  
- [ ] Reduce power  
- [ ] Increase airspeed  
  
**3.2.6 Fuel Pressure (Low)**  
  
- [ ] **1.** Fuel quantity — check  
- [ ] **2.** Fuel valve — check ON  
- [ ] **3.** Fuel pumps — ON  
  
**If FUEL PRESS warning remains:**  
  
- [ ] **4.** Fuel valve — EMERGENCY  
- [ ] **5.** Fuel pumps — OFF  
  
If FUEL PRESS warning still remains:  
Prepare per 3.3.4 — ENGINE FAILURE IN FLIGHT.  
  
**3.2.7 Alternator Amps (> 70 A)**  
  
- [ ] **1.** Electrical equipment — switch OFF as necessary to reduce electric load  
  
**If problem does not clear:**  
  
- [ ] **2.** Land on the nearest suitable airfield.  
  
**3.2.8 Alternator Fail**  
  
- [ ] **1.** Circuit breakers — check  
- [ ] **2.** ESSENTIAL BUS — ON  
- [ ] **3.** Electrical equipment — switch OFF all equipment not needed  
- [ ] **4.** Land on the nearest suitable airfield  
  
### 3.3 Engine Problems  
  
**3.3.1 Engine Problems on Ground**  
  
- [ ] **1.** POWER lever — IDLE  
- [ ] **2.** Brakes — as required  
  
**3.3.2 Engine Problems During Take-Off**  
  
(a) Take-Off Can Still Be Aborted  
  
Land straight ahead:  
- [ ] **1.** POWER lever — IDLE  
  
On the ground:  
- [ ] **2.** Brakes — as required  
- [ ] Fuel valve — OFF  
- [ ] ENGINE MASTER — OFF  
- [ ] ELECTRIC MASTER — OFF  
  
(b) Take-Off Can No Longer Be Aborted  
  
- [ ] **1.** Airspeed — immediate pitch down to avoid airspeed reduction  
- [ ] **2.** POWER lever — check MAX  
- [ ] **3.** Fuel pumps — check ON  
- [ ] **4.** VOTER switch — check AUTO  
  
**3.3.3 Engine Troubleshooting in Flight**  
  
- [ ] **1.** Airspeed — 88 KIAS  
- [ ] **2.** POWER lever — MAX  
  
**If ECU A and ECU B cautions appear simultaneously** (with load unchanged, perceived thrust reduced, engine running rough):  
  
- [ ] **3.** POWER lever — IDLE for 1 second  
- [ ] **4.** POWER lever — slowly increase to 1975 RPM  
  
**If engine shows power loss during increase:**  
  
- [ ] **5.** POWER lever — IDLE for 1 second  
- [ ] **6.** POWER lever — slowly increase, stop prior to the previously observed power loss RPM  
  
> **WARNING:** Do not increase POWER lever past 1975 RPM or the RPM from step 6. Do not exceed this setting.  
  
- [ ] **7.** Land at the next suitable airfield.  
  
**Otherwise, attempt to restore normal engine operation:**  
  
- [ ] **3.** Circuit breakers — check / reset if necessary  
  
If restored — continue flight and land as soon as possible.  
  
- [ ] **4.** VOTER switch — swap between ECU A and B  
  
If one setting restores operation — maintain ECU setting and land as soon as possible.  
  
- [ ] **5.** VOTER switch — switch back to AUTO  
  
If restored — land as soon as possible.  
  
- [ ] **6.** Fuel valve — EMERGENCY  
  
If restored — land as soon as possible. Remain within maximum allowable lateral imbalance.  
  
- [ ] **7.** Fuel valve — NORMAL  
- [ ] **8.** Alternate air — OPEN  
- [ ] **9.** POWER lever — apply power as required  
  
If normal engine operation cannot be restored, prepare for 3.3.4 and land as soon as possible.  
⸻  
### 3.3.4 Engine Failure in Flight  
  
> **WARNING:** Control over the flight attitude has priority ("first fly the airplane").  
  
- [ ] **1.** Airspeed — 88 KIAS  
- [ ] **2.** Flaps — UP  
  
**If remaining altitude is sufficient for restart:** Attempt engine restart per 3.3.5.  
  
**If remaining altitude is NOT sufficient:** Carry out emergency landing per 3.7.1.  
⸻  
### 3.3.5 Restarting the Engine in Flight  
  
> **NOTE:** Maximum restart altitude: 16,400 ft (immediate restarts); 10,000 ft (restarts within two minutes). If engine cools more than two minutes, restart may not be possible.  
  
- [ ] **1.** Airspeed — 88 KIAS  
- [ ] **2.** POWER lever — IDLE  
- [ ] **3.** VOTER switch — check AUTO  
- [ ] **4.** Fuel valve — check NORMAL  
- [ ] **5.** Alternate air — as required  
- [ ] **6.** Fuel quantity — check  
- [ ] **7.** Fuel transfer pump — as required  
- [ ] **8.** ELECTRIC MASTER — check ON  
- [ ] **9.** ENGINE MASTER — check ON  
  
**If engine does not start:**  
  
- [ ] **10.** Fuel valve — EMERGENCY  
  
**If engine still does not start — adopt glide configuration:**  
  
- [ ] **11.** Flaps — UP  
- [ ] **12.** Airspeed — 88 KIAS  
  
> **NOTE:** Glide ratio is 9.7; for every 1,000 ft altitude loss, maximum horizontal distance in still air is 1.59 NM.  
  
Carry out emergency landing per 3.7.1.  
  
> **CAUTION:** Engine restart following engine fire should only be attempted if safe emergency landing cannot be made.  
  
- [ ] **13.** AVIONIC MASTER — ON, if required  
⸻  
### 3.3.6 Defective RPM Regulating System  
  
> **WARNING:** Reduced engine performance should be anticipated.  
  
### (a) Oscillating RPM  
  
- [ ] **1.** Power setting — change  
  
**If problem does not clear:**  
- [ ] **2.** VOTER switch — swap between ECU A and B  
  
**If problem does not clear:**  
- [ ] **3.** VOTER switch — AUTO  
- [ ] **4.** Land on the nearest suitable airfield.  
  
### (b) Propeller Overspeed  
- [ ] **1.** POWER lever — reduce to not exceed 2300 RPM  
- [ ] **2.** Airspeed — 88 KIAS  
- [ ] **3.** Flaps — check UP  
  
**After RPM stabilizes below 2300 RPM:**  
  
- [ ] **4.** Airspeed — as required, do not exceed 2300 RPM  
- [ ] **5.** POWER lever — as required, do not exceed 2300 RPM  
  
**If problem does not clear:**  
- [ ] **6.** VOTER switch — swap between ECU A and B  
- [ ] **7.** Land on the nearest suitable airfield.  
  
**If increased climb rate is required:**  
- [ ] **8.** Flaps — T/O position  
- [ ] **9.** Airspeed — 72 KIAS  
- [ ] **10.** POWER lever — as required, do not exceed 2300 RPM  
  
### (c) Propeller Underspeed  
  
- [ ] **1.** POWER lever — as required  
  
**If problem does not clear:**  
- [ ] **2.** VOTER switch — swap between ECU A and B  
  
**If problem does not clear:**  
- [ ] **3.** VOTER switch — AUTO  
- [ ] **4.** POWER lever — as required  
  
> **WARNING:** Propeller RPM will drop. No climb performance or go-around power may be available.  
  
- [ ] **5.** Land on the nearest suitable airfield.  
⸻  
### 3.3.7 Fuel Transfer Pump Failure  
  
- [ ] **1.** Fuel quantity — check  
  
**If main tank fuel quantity is low:**  
  
- [ ] **2.** Fuel valve — EMERGENCY  
- [ ] **3.** Fuel pumps — OFF  
  
> **WARNING:** Switch the fuel valve back to NORMAL before the auxiliary tank reads zero.   
> 
> **CAUTION:** When set to EMERGENCY, fuel is transferred from auxiliary to main tank at ~45 US gal/h.  
  
- [ ] **4.** AUX tank — monitor quantity  
- [ ] **5.** MAIN tank — monitor quantity  
  
> **NOTE:** AUX tank quantity must not be less than 1 US gal and MAIN tank quantity must not be more than 14 US gal.  
  
- [ ] **6.** Fuel valve — NORMAL  
- [ ] **7.** Land as soon as practicable.  
⸻  
## 3.4 Failures in the Electrical System  
  
### 3.4.1 Complete Failure of the Electrical System  
  
- [ ] **1.** Circuit breakers — check IN  
- [ ] **2.** ESSENTIAL BUS — ON  
  
**If there is still no electrical power:**  
  
- [ ] **3.** EMERGENCY switch (if installed) — ON  
- [ ] **4.** Flood light, if necessary — ON  
- [ ] **5.** POWER — set based on lever positions and engine noise  
- [ ] **6.** Prepare landing with flaps in the given position. Refer to 4B.5.  
- [ ] **7.** Land on the nearest suitable airfield.  
  
> **WARNING:** Engine stoppage may occur depending on failure mode. Backup battery powers ECU B for at least 30 minutes.   
> 
> **NOTE:** Backup artificial horizon and flood light have power for at least 1.5 hours.  

⸻  
### 3.4.2 High Current  
  
- [ ] **1.** ESSENTIAL BUS — ON  
- [ ] **2.** ENGINE SYSTEM DISPLAY (if G1000) — select ENGINE and SYSTEM softkey on MFD  
- [ ] **3.** Circuit breakers — check IN  
- [ ] **4.** Ammeter/Voltmeter — monitor  
- [ ] **5.** Land on the nearest suitable airfield.  
⸻  
### 3.4.3 Starter Malfunction  
  
**On Ground:**  
- [ ] **1.** POWER lever — IDLE  
- [ ] **2.** ENGINE MASTER — OFF  
- [ ] **3.** ELECTRIC MASTER — OFF  
  
Terminate flight preparation!  
  
**In Flight:** Land as soon as possible.  
⸻  
## 3.5 Smoke and Fire  
  
### 3.5.1 Smoke and Fire on Ground  
  
### (a) Engine Fire When Starting on the Ground  
  
- [ ] **1.** Fuel valve — OFF  
- [ ] **2.** Fuel transfer pump — OFF  
- [ ] **3.** ENGINE MASTER — OFF  
- [ ] **4.** Fuel pumps — OFF  
- [ ] **5.** ELECTRIC MASTER — OFF  
  
**After standstill:**  
  
- [ ] **6.** Canopy — open  
- [ ] **7.** Airplane — evacuate immediately  
  
### (b) Electrical Fire with Smoke on the Ground  
  
- [ ] **1.** ELECTRIC MASTER — OFF  
  
**If engine is running:**  
  
- [ ] **2.** POWER lever — IDLE  
- [ ] **3.** ENGINE MASTER — OFF  
- [ ] **4.** Fuel pumps — OFF  
  
**When engine has stopped:**  
  
- [ ] **5.** Canopy — open  
- [ ] **6.** Airplane — evacuate immediately  
⸻  
### 3.5.2 Smoke and Fire During Take-Off  
  
### (a) If Take-Off Can Still Be Aborted  
  
- [ ] **1.** POWER lever — IDLE  
- [ ] **2.** Cabin heat — OFF  
- [ ] **3.** Brakes — apply, bring the airplane to a stop  
- [ ] **4.** Fuel valve — OFF  
- [ ] **5.** Fuel transfer pump — OFF  
- [ ] **6.** ENGINE MASTER — OFF  
- [ ] **7.** Fuel pumps — OFF  
- [ ] **8.** ELECTRIC MASTER — OFF  
  
**After standstill:**  
  
- [ ] **9.** Canopy — open  
- [ ] **10.** Airplane — evacuate immediately  
  
### (b) If Take-Off Cannot Be Aborted  
  
- [ ] **1.** Cabin heat — OFF  
- [ ] **2.** If possible, fly along a short-cut traffic circuit and land on the airfield.  
  
> **WARNING:** If height has not been reached for a return, carry out a straight-ahead emergency landing. Do NOT turn back. Turning back can be fatal.  
  
**After climbing to a height from which the selected landing area can be reached safely:**  
  
- [ ] **3.** Fuel valve — OFF  
- [ ] **4.** Fuel transfer pump — OFF  
- [ ] **5.** Cabin heat — OFF  
- [ ] **6.** ENGINE MASTER — OFF  
- [ ] **7.** Fuel pumps — OFF  
- [ ] **8.** ELECTRIC MASTER — OFF  
- [ ] **9.** Emergency windows — open if necessary  
- [ ] **10.** Carry out emergency landing with engine off per 3.7.1.  
  
**When airplane has stopped:**  
  
- [ ] **11.** Canopy — open  
- [ ] **12.** Airplane — evacuate immediately  
⸻  
### 3.5.3 Smoke and Fire in Flight  
  
> **WARNING:** Prepare to land without delay. If fire cannot be visually verified as extinguished, land immediately.  
  
### (a) Engine Fire in Flight  
  
- [ ] **1.** Cabin heat — OFF  
- [ ] **2.** Select appropriate emergency landing area.  
  
**When landing area is certain to be reached:**  
  
- [ ] **3.** Fuel valve — OFF  
- [ ] **4.** POWER lever — MAX  
- [ ] **5.** Emergency windows — open if required  
- [ ] **6.** Land immediately per 3.7.1.  
  
**When airplane has stopped:**  
  
- [ ] **7.** Canopy — open  
- [ ] **8.** Airplane — evacuate immediately  
  
### (b) Electrical Fire with Smoke in Flight  
  
- [ ] **1.** EMERGENCY switch (if installed) — ON  
- [ ] **2.** AVIONIC MASTER — OFF  
- [ ] **3.** ELECTRIC MASTER — OFF  
- [ ] **4.** Cabin heat — OFF  
- [ ] **5.** Emergency windows — open if required  
- [ ] **6.** Land immediately per 3.7.1.  
  
> **WARNING:** Switching OFF ELECTRIC MASTER will cause total failure of all electronic/electric equipment, including attitude gyro. EMERGENCY switch (if installed) will supply backup battery to attitude gyro and flood light.  
  
**When airplane has stopped:**  
  
- [ ] **7.** Canopy — open  
- [ ] **8.** Airplane — evacuate immediately  
⸻  
## 3.6 Gliding  
  
- [ ] **1.** Flaps — UP  
- [ ] **2.** Airspeed — 88 KIAS  
  
> **NOTE:** Glide ratio is 9.7; for every 1,000 ft altitude loss, maximum horizontal distance in still air is 1.59 NM (2.94 km). Propeller will continue to windmill.   
> 
> **NOTE:** Without wheel fairings, glide ratio is reduced to 9.4; 1.54 NM (2.85 km) per 1,000 ft.  

⸻  
## 3.7 Emergency Landings  
  
### 3.7.1 Emergency Landing with Engine Off  
  
- [ ] **1.** Adjustable backrests (if installed) — adjust to the upright position; verify proper fixation  
- [ ] **2.** ENGINE MASTER — check OFF  
- [ ] **3.** Fuel transfer pump — OFF  
- [ ] **4.** Fuel pumps — OFF  
- [ ] **5.** Fuel valve — OFF  
- [ ] **6.** AVIONIC MASTER — OFF  
- [ ] **7.** Safety harnesses — check fastened and tightened  
  
**When sure of making the landing area:**  
  
- [ ] **8.** FLAPS — T/O or LDG, as required  
  
**9.** Approach speed — see table below:  

| Flaps | 940 kg (2072 lb) | 1000 kg (2205 lb) | 1080 kg (2381 lb) | 1160 kg (2557 lb) | 1216 kg (2681 lb) | 1280 kg (2822 lb) |
| ----- | ---------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- |
| T/O | 68 KIAS | 70 KIAS | 73 KIAS | 76 KIAS | 77 KIAS | 78 KIAS |
| LDG | 66 KIAS | 69 KIAS | 72 KIAS | 74 KIAS | 76 KIAS | 77 KIAS |
  
  
- [ ] **10.** ELECTRIC MASTER — OFF  
- [ ] **11.** Touch down — lowest practical speed  
⸻  
### 3.7.2 Landing with a Defective Tire on the Main Landing Gear  
  
- [ ] **1.** Advise ATC.  
- [ ] **2.** Land the airplane at the edge of the runway on the side of the intact tire.  
- [ ] **3.** Land with one wing low — the wing on the side of the intact tire should be held low.  
- [ ] **4.** Maintain direction using the rudder, supported by brake use. Apply brake strongly if necessary, even to wheel lock if needed.  
⸻  
### 3.7.3 Landing with Defective Brakes  
  
A landing on grass is recommended to reduce landing run due to greater rolling resistance.  
  
> **WARNING:** If sufficient time remains, after safe touchdown reduce fire risk:  

- Fuel valve — OFF  
- ENGINE MASTER — OFF  
- Fuel pumps — OFF  
- ELECTRIC MASTER — OFF  
⸻  
## 3.8 Recovery from an Unintentional Spin  
  
> **CAUTION:** Steps 1 to 4 must be carried out immediately and simultaneously.  
  
- [ ] **1.** POWER lever — IDLE  
- [ ] **2.** Ailerons — neutral  
- [ ] **3.** Rudder — full deflection against direction of spin  
- [ ] **4.** Elevator (control stick) — fully forward  
  
**When rotation has stopped:**  
  
- [ ] **5.** Flaps — UP  
- [ ] **6.** Rudder — neutral  
- [ ] **7.** Elevator (control stick) — pull carefully  
- [ ] **8.** Return airplane from descending to normal flight attitude. Do not exceed vNE = 172 KIAS.  
⸻  
## 3.9 Other Emergencies  
  
### 3.9.1 Icing  
  
**Unintentional flight into icing conditions:**  
  
- [ ] **1.** Leave the icing area (change altitude or turn back to reach zones with higher ambient temperature)  
- [ ] **2.** Pitot heating — ON  
- [ ] **3.** Cabin heat — ON  
- [ ] **4.** Cabin air — DEFROST  
- [ ] **5.** POWER lever — increase power to prevent ice build-up on propeller blades; apply power changes periodically  
- [ ] **6.** Alternate air — OPEN  
- [ ] **7.** Emergency windows — open if required  
  
> **CAUTION:** Ice build-up increases the stalling speed.  
  
- [ ] **8.** ATC — advise if an emergency is expected  
  
> **CAUTION:** When Pitot heating fails, expect loss of airspeed indication.  

⸻  
### 3.9.2 Suspicion of Carbon Monoxide Contamination in the Cabin  
  
- [ ] **1.** Cabin heat — OFF  
- [ ] **2.** Ventilation — open  
- [ ] **3.** Emergency windows — open  
- [ ] **4.** Forward canopy — unlatch, push up and lock in 'Cooling Gap' position  
  
> **CAUTION:** Maximum demonstrated airspeed for opening the front canopy in flight is 117 KIAS.  

⸻  
### 3.9.3 Unlocked Doors  
  
- [ ] **1.** Airspeed — reduce immediately  
- [ ] **2.** Canopy — check visually if closed  
- [ ] **3.** Rear door — check visually if closed  
  
**Canopy unlocked:**  
  
- [ ] **4.** Airspeed — below 140 KIAS  
- [ ] **5.** Land at next suitable airfield.  
  
**Rear door unlocked:**  
  
- [ ] **4.** Airspeed — below 140 KIAS  
- [ ] **5.** Land at the next suitable airfield.  
  
> **WARNING:** Do not try to lock the rear door in flight. The safety latch may disengage and the door opens, usually resulting in separation of the door from the airplane.   
> 
> **NOTE:** If the rear door has been lost, the airplane can be safely flown to the next suitable airfield.  

⸻  
⸻  
  
  
## CHAPTER 4A — NORMAL OPERATING PROCEDURES  
  
### 4A.5.1 Pre-Flight Inspection  
  
### I. Cabin Check  
- [ ] a) MET, NAV, Mass & CG — flight planning completed  
- [ ] b) Airplane documents — complete and up-to-date  
- [ ] c) ELECTRIC MASTER — OFF, pull out key  
- [ ] d) ENGINE MASTER — check OFF  
- [ ] e) VOTER switch — check AUTO  
- [ ] f) Fuel valve — locked, in NORMAL position  
- [ ] g) Front canopy & rear door — clean, undamaged; check locking mechanism function  
- [ ] h) All electrical equipment — OFF  
- [ ] i) Circuit breakers — check all IN (if one has popped: investigate)  
- [ ] j) POWER lever — check condition, freedom of movement, full travel and friction adjustment  
- [ ] k) POWER lever — IDLE  
- [ ] l) ELECTRIC MASTER — ON  
- [ ] m) Fuel quantity — check, use alternate means  
- [ ] n) Position lights, strobe lights (ACL) — check OFF  
- [ ] o) Taxi lights, landing lights — check OFF  
- [ ] p) ELECTRIC MASTER — OFF  
- [ ] q) Foreign objects — check  
- [ ] r) Controls and trim — free and correct  
- [ ] s) Emergency axe (if installed) — stowed and secured  
- [ ] t) Baggage — stowed and secured  
  
### II. Walk-Around Check, Visual Inspection  
  
1. Left Main Landing Gear:  
- [ ] a) Landing gear strut or fairing (if installed) — visual inspection  
- [ ] b) Wear, tread depth of tire — check  
- [ ] c) Tire, wheel, brake — visual inspection  
- [ ] d) Brakes — check for leaks  
- [ ] e) Slip marks — visual inspection  
- [ ] f) Chocks — remove  
  
2. Left Wing:  
- [ ] a) Entire wing surface — visual inspection  
- [ ] b) Step — visual inspection  
- [ ] c) Air intake on lower wing surface — visual inspection  
- [ ] d) Winter baffle of air intake on lower wing surface (if installed) — consider removal depending on OAT; verify proper mounting  
- [ ] e) Openings on lower surface — check for foreign objects and for traces of fuel  
- [ ] f) Tank drain — drain to check for water and sediment (drain until free of contamination)  
- [ ] g) Stall warning — check function (suction)  
- [ ] h) Tank filler — check closed (for fuel qty. check use alternate means)  
- [ ] i) Tank air outlet in lower surface — visual inspection  
- [ ] j) Pitot probe — clean, orifices clear, attachment secure (no loose or missing screws)  
- [ ] k) Landing/taxi light — visual inspection  
- [ ] l) Winglet — visual inspection  
- [ ] m) Position light, strobe light (ACL) — visual inspection  
- [ ] n) Tie-down — check, clear  
- [ ] o) 2 stall strips on wing — visual inspection  
- [ ] p) Aileron and linkage — visual inspection  
- [ ] q) Aileron hinges and safety pin — visual inspection  
- [ ] r) Foreign objects in aileron paddle — visual inspection  
- [ ] s) Trim tab — visual inspection  
- [ ] t) Flap and linkage — visual inspection  
- [ ] u) Flap hinges and safety pin — visual inspection  
- [ ] v) Static discharger — visual inspection  
- [ ] w) Fuel cooler inlet baffle (if installed) — verify OAT permits use; check for improper mounting or obvious damage  
  
3. Fuselage, Left Side:  
- [ ] a) Canopy, left side — visual inspection  
- [ ] b) Door lock (if installed) — unlocked, key removed  
- [ ] c) Rear cabin door & window — visual inspection  
- [ ] d) Fuselage skin — visual inspection  
- [ ] e) Antennas — visual inspection  
- [ ] f) Static source — check for blockage  
  
4. Empennage:  
- [ ] a) Stabilizers and control surfaces — visual inspection  
- [ ] b) Hinges — visual inspection  
- [ ] c) Elevator trim tab — visual inspection; check for movement and safety wire  
- [ ] d) Rudder tab — visual inspection  
- [ ] e) Tie-down — check, clear  
- [ ] f) Tail skid and lower fin — visual inspection  
- [ ] g) Static dischargers — visual inspection  
  
5. Fuselage, Right Side:  
- [ ] a) Fuselage skin — visual inspection  
- [ ] b) Static source — check for blockage  
- [ ] c) Rear window — visual inspection  
- [ ] d) Canopy, right side — visual inspection  
  
6. Right Wing:  
- [ ] a) Flap and linkage — visual inspection  
- [ ] b) Flap hinges and safety pin — visual inspection  
- [ ] c) Aileron and linkage — visual inspection  
- [ ] d) Aileron hinges and safety pin — visual inspection  
- [ ] e) Foreign objects in aileron paddle — visual inspection  
- [ ] f) Winglet — visual inspection  
- [ ] g) Position light, strobe light (ACL) — visual inspection  
- [ ] h) Tie-down — check, clear  
- [ ] i) Entire wing surface — visual inspection  
- [ ] j) 2 stall strips on wing — visual inspection  
- [ ] k) Tank air outlet in lower surface — visual inspection  
- [ ] l) Tank filler — visual check (for fuel qty. check use alternate means)  
- [ ] m) Openings on lower surface — check for foreign objects and for traces of fuel  
- [ ] n) Tank drain — drain to check for water and sediment (drain until free of contamination)  
- [ ] o) Step — visual inspection  
- [ ] p) Static discharger — visual inspection  
  
7. Right Main Landing Gear:  
- [ ] a) Landing gear strut or fairing (if installed) — visual inspection  
- [ ] b) Wear, tread depth of tires — check  
- [ ] c) Tire, wheel, brake — visual inspection  
- [ ] d) Brakes — check for leaks  
- [ ] e) Slip marks — visual inspection  
- [ ] f) Chocks — remove  
  
8. Front Fuselage:  
- [ ] a) Engine oil level — check dipstick (inspection door on left side)  
- [ ] b) Gearbox oil level — check visually (inspection door on left side)  
- [ ] c) Cowling — visual inspection  
- [ ] d) 4 air intakes on front cowling — check  
- [ ] e) 2 air intakes on RH fuselage and cowling — check  
- [ ] f) 1 air intake on LH fuselage — check  
- [ ] g) Propeller — visual inspection  
- [ ] h) Spinner including attachment screws — visual inspection  
- [ ] i) Nose landing gear strut — visual inspection  
- [ ] j) Tie-down (if installed) — check, clear  
- [ ] k) Tire and wheel — visual inspection; check slip marks  
- [ ] l) Wear, tread depth of tire — check  
- [ ] m) Wheel fairing (if installed) — visual inspection  
- [ ] n) Tow bar — removed  
- [ ] o) Chocks — remove  
- [ ] p) Exhaust — visual inspection  
  
9. Underside:  
- [ ] a) Antennas — visual inspection  
- [ ] b) Gascolator — pull down on drain to check for water and sediment (drain until free of contamination)  
- [ ] c) Venting pipes — check for blockage  
- [ ] d) Fuselage underside — check for excessive contamination particularly by oil, fuel or other fluids  
  
### 4A.5.2 Before Starting Engine  
- [ ] 1. Pre-flight inspection — complete  
- [ ] 2. Rudder pedals — adjusted and locked  
- [ ] 3. Passengers — instructed  
- [ ] 4. Adjustable backrests (if installed) — adjust to the upright position; verify proper fixation  
- [ ] 5. Safety harnesses — all fastened  
- [ ] 6. Rear door — closed and locked  
- [ ] 7. Door lock (if installed) — unlocked, key removed  
- [ ] 8. Front canopy — Position 1 or 2 ("cooling gap")  
- [ ] 9. Canopy lock (if installed) — unlocked, key removed  
- [ ] 10. Parking brake — set  
- [ ] 11. Flight controls — free movement  
- [ ] 12. Trim wheel — T/O  
- [ ] 13. POWER lever — check IDLE  
- [ ] 14. Friction device on POWER lever — adjusted  
- [ ] 15. Alternate air — check CLOSED  
- [ ] 16. Alternate static valve — check CLOSED  
- [ ] 17. VOTER switch — check AUTO  
- [ ] 18. Fuel pumps — check OFF  
- [ ] 19. AVIONIC MASTER — check OFF  
- [ ] 20. ELECTRIC MASTER — ON  
- [ ] 21. G1000 (if installed) — wait until power-up completed; press ENT on MFD to acknowledge  
- [ ] 22. White Wire annunciator panel (if installed) — check and press acknowledge button  
- [ ] 23. COOL LVL caution (G1000) or WATERLEV caution (SED) — check OFF  
- [ ] 24. Fuel temperature — check  
  
### 4A.5.3 Starting Engine  
- [ ] 1. Strobe lights (ACL) — ON  
- [ ] 2. ENGINE MASTER — ON  
- [ ] 3. Annunciations / GLOW ON (G1000) or GLOW (White Wire) — check ON  
- [ ] 4. Annunciations / engine indications — check  
After GLOW indication is extinguished:  
- [ ] 5. START KEY — START as required / release when engine has started  
- [ ] 6. Annunciations / engine indications — check OK/normal range  
- [ ] 7. Annunciations / STARTER (G1000) or START (White Wire) — check OFF  
- [ ] 8. Annunciations / Oil pressure — check OK  
- [ ] 9. Circuit breakers — check all IN  
- [ ] 10. Idle RPM — check, 710 ±30 RPM (above 7,000 ft pressure altitude idle RPM might be higher)  
  
### 4A.5.4 Before Taxiing  
- [ ] 1. AVIONIC MASTER — ON  
- [ ] 2. Power lever — as required, max. 50% if engine temperature below green range  
- [ ] 3. Electrical equipment — ON as required  
- [ ] 4. Flight instruments and avionics — set as required  
- [ ] 5. Flood light — ON, test function, as required  
- [ ] 6. Pitot heating — ON; check annunciation and observe increase in alternator load  
- [ ] 7. Pitot heating — OFF  
- [ ] 8. Strobe lights (ACLs) — check ON  
- [ ] 9. Position lights, landing and taxi lights — as required  
- [ ] 10. Primary flight display PFD (if G1000 and autopilot GFC 700 installed) — NO AUTOPILOT ANNUNCIATIONS  
- [ ] 11. Autopilot disconnect tone (if autopilot GFC 700 installed) — NOTE  
- [ ] 12. MANUAL ELECTRIC TRIM — TEST: Press AP DISC button down and hold while commanding trim. Manual electric trim should not operate either nose up or nose down.  
- [ ] 13. AUTOPILOT (if G1000 and GFC 700 installed) — engage by pressing AP button  
- [ ] 14. AP DISC switch (if G1000 and GFC 700 installed) — press; verify autopilot disconnects; check tone  
- [ ] 15. TRIM — set to take-off position manually  
  
### 4A.5.5 Taxiing  
- [ ] 1. Parking brake — release  
- [ ] 2. Brakes — test  
- [ ] 3. Flight instrumentation and avionics — check for correct indications  
- [ ] 4. Fuel pumps — check OFF  
  
### 4A.5.6 Before Take-Off  
- [ ] 1. Position airplane into wind if possible.  
- [ ] 2. Parking brake — set  
- [ ] 3. Adjustable backrests (if installed) — verify upright position and proper fixation  
- [ ] 4. Safety harnesses — fastened  
- [ ] 5. Rear door — check closed and locked  
- [ ] 6. Front canopy — closed and locked  
- [ ] 7. Door warning (DOOR OPEN / DOORS) — check no indication  
- [ ] 8. Annunciations / engine indications — check OK / normal range  
- [ ] 9. Circuit breakers — check pressed in  
- [ ] 10. Longitudinal trim — set T/O  
- [ ] 11. Fuel valve — check NORMAL  
- [ ] 12. FLAPS — check function & indicator / set T/O  
- [ ] 13. Flight controls — unrestricted free movement, correct sense  
- [ ] 14. Pitot heating — ON, if required  
- [ ] 15. Landing light — ON, if required  
ECU / Fuel Pump Test Sequence:  
- [ ] 1. POWER lever — IDLE  
- [ ] 2. Propeller RPM — check below 1000 RPM  
- [ ] 3. Fuel pumps — check OFF  
- [ ] 4. VOTER switch — check AUTO  
- [ ] 5. All engine temperatures — check in the green range  
- [ ] 6. Parking brake — check set  
- [ ] 7. ECU TEST button — press and hold  
- [ ] 8. ECU A/B FAIL (G1000) or ECU A/B (White Wire) lights — verify both OFF. Test sequence completed.  
- [ ] 9. ECU TEST button — release  
- [ ] 10. VOTER switch — ECU A  
- [ ] 11. Engine — check running without a change  
- [ ] 12. VOTER switch — AUTO  
- [ ] 13. Engine — check running without a change  
- [ ] 14. VOTER switch — ECU B  
- [ ] 15. Engine — check running without a change  
- [ ] 16. VOTER switch — AUTO  
Available Power Check:  
- [ ] 1. POWER lever — MAX for 10 seconds  
- [ ] 2. Annunciations — check OK / normal range  
- [ ] 3. Instruments — check within normal range  
- [ ] 4. RPM — stabilizes at 2200 to 2300 RPM (min. 2100 RPM below -10°C/14°F)  
- [ ] 5. LOAD indication — stabilizes at 88% to 100%  
- [ ] 6. POWER lever — IDLE  
- [ ] 7. Engine instruments — check in green range  
- [ ] 8. Fuel pumps — ON  
- [ ] 9. Parking brake — release  
  
### 4A.5.7 Take-Off  
Normal Take-Off Procedure  
- [ ] 1. Transponder — as required  
- [ ] 2. POWER lever — MAX  
- [ ] 3. Elevator — neutral  
- [ ] 4. Rudder — maintain direction  
- [ ] 5. Nose wheel lift-off (vR):  

| 940 kg (2072 lb) | 1000 kg (2205 lb) | 1100 kg (2425 lb) | 1200 kg (2646 lb) | 1280 kg (2822 lb) and above |
| ---------------- | ----------------- | ----------------- | ----------------- | --------------------------- |
| 56 KIAS | 58 KIAS | 61 KIAS | 65 KIAS | 67 KIAS |
  
6. Airspeed for initial climb:  

| 940 kg (2072 lb) | 1000 kg (2205 lb) | 1100 kg (2425 lb) | 1200 kg (2646 lb) | 1280 kg (2822 lb) and above |
| ---------------- | ----------------- | ----------------- | ----------------- | --------------------------- |
| 62 KIAS | 65 KIAS | 67 KIAS | 70 KIAS | 72 KIAS |
  
  
Above a safe height:  
- [ ] 7. Landing light — OFF  
- [ ] 8. Fuel pumps — OFF  
- [ ] 9. POWER lever — reduce to 92% load  
  
### 4A.5.8 Climb  
Procedure for Take-Off Climb  
- [ ] 1. Flaps — T/O  
- [ ] 2. Airspeed — 72 KIAS  
- [ ] 3. POWER lever — 92% or maximum 2100 RPM  
- [ ] 4. Annunciations / engine indications — monitor  
- [ ] 5. Rudder — as required  
Cruise Climb  
- [ ] 1. Flaps — UP  
- [ ] 2. Airspeed — 88 KIAS  
- [ ] 3. POWER lever — 92% or maximum 2100 RPM  
- [ ] 4. Annunciations / engine indications — monitor  
- [ ] 5. Rudder — as required  
  
### 4A.5.9 Cruise  
- [ ] 1. Flaps — UP  
- [ ] 2. POWER lever — up to 92% or maximum 2100 RPM  
- [ ] 3. Trim — as required  
- [ ] 4. Fuel transfer — repeat as required (per 4A.5.10)  
  
### 4A.5.10 Fuel Transfer  
- [ ] 1. Fuel transfer switch — ON  
- [ ] 2. Fuel transfer switch — OFF, if required  
  
### 4A.5.11 Descent  
- [ ] 1. POWER lever — as required  
- [ ] 2. Airspeed — as required  
- [ ] 3. Trim — as required  
- [ ] 4. Annunciations / engine indications — monitor  
  
### 4A.5.12 Approach & Landing  
Approach:  
- [ ] 1. Adjustable backrests (if installed) — adjust to upright position; verify proper fixation  
- [ ] 2. Safety harnesses — check fastened and tightened  
- [ ] 3. Controls — no interference by foreign objects  
- [ ] 4. Landing light — as required  
- [ ] 5. Fuel pumps — ON  
- [ ] 6. Parking brake — check released  
- [ ] 7. Trim — as required  
Before Landing:  
8. Airspeed — see table below:  

| Flaps | 940 kg (2072 lb) | 1000 kg (2205 lb) | 1100 kg (2425 lb) | 1200 kg (2646 lb) | 1216 kg (2681 lb) | 1280 kg (2822 lb) |
| ----- | ---------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- |
| T/O | 68 KIAS | 70 KIAS | 74 KIAS | 77 KIAS | 77 KIAS | 78 KIAS |
| LDG | 66 KIAS | 68 KIAS | 72 KIAS | 76 KIAS | 76 KIAS | 77 KIAS |
  
  
- [ ] 9. FLAPS — as required  
- [ ] 10. POWER lever — as required  
- [ ] 11. Trim — as required  
12. Final approach speed:  

| Flaps | 940 kg (2072 lb) | 1000 kg (2205 lb) | 1100 kg (2425 lb) | 1200 kg (2646 lb) | 1216 kg (2681 lb) | 1280 kg (2822 lb) |
| ----- | ---------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- |
| LDG | 66 KIAS | 68 KIAS | 72 KIAS | 76 KIAS | 76 KIAS | 77 KIAS |
  
  
##   
### 4A.5.13 Go-Around  
- [ ] 1. POWER lever — MAX  
- [ ] 2. Airspeed — 72 KIAS  
- [ ] 3. Flaps — T/O  
Above a safe height:  
- [ ] 4. Airspeed — 88 KIAS  
- [ ] 5. Flaps — UP  
  
### 4A.5.14 After Landing  
- [ ] 1. POWER lever — IDLE  
- [ ] 2. Brakes — as required  
- [ ] 3. Transponder — OFF / STBY  
- [ ] 4. Pitot heating — OFF  
- [ ] 5. Avionics — as required  
- [ ] 6. Lights — as required  
- [ ] 7. Flaps — UP  
- [ ] 8. Fuel pumps — OFF  
  
### 4A.5.15 Engine Shut-Down  
- [ ] 1. Parking brake — set  
- [ ] 2. POWER lever — up to 10% load for 1 minute  
- [ ] 3. Engine indications — check  
- [ ] 4. ELT — check not transmitting on 121.5 MHz  
- [ ] 5. AVIONIC MASTER — OFF  
- [ ] 6. Electrical consumers — OFF  
- [ ] 7. ENGINE MASTER — OFF  
- [ ] 8. Strobe — OFF  
- [ ] 9. ELECTRIC MASTER — OFF  
  
### 4A.5.16 Post Flight Inspection  
- [ ] 1. Record any problem found in flight and during the post-flight check in the log book.  
- [ ] 2. Park the airplane.  
- [ ] 3. If necessary, moor the airplane.  
  
### 4A.5.17 Parking  
- [ ] 1. Parking brake — release, use chocks  
- [ ] 2. Airplane — moor, if unsupervised for extended period  
- [ ] 3. Pitot probe — cover  
  
  
  
## CHAPTER 4B — ABNORMAL OPERATING PROCEDURES  
  
### 4B.1 Precautionary Landing  
- [ ] **1.** Select appropriate landing area.  
- [ ] **2.** Consider wind.  
- [ ] **3.** Approach: Overfly the landing area at a suitable height if possible to recognize obstacles and assess wind speed/direction.  
- [ ] **4.** ATC — advise  
  
Perform procedures per 4A.5.12 — APPROACH & LANDING.  
  
- [ ] **5.** Touchdown — with the lowest possible airspeed  
  
**If sufficient time remains, after safe touchdown reduce fire risk:**  
  
- [ ] **6.** ENGINE MASTER — OFF  
- [ ] **7.** Fuel valve — OFF  
- [ ] **8.** ELECTRIC MASTER — OFF  
⸻  
## 4B.2 Instrument Indications Outside of Green Range  
  
### 4B.2.1 RPM  
  
**High RPM:**  
- [ ] **1.** Reduce power.  
- [ ] **2.** Keep RPM within the green range using the POWER lever.  
  
> **NOTE:** An RPM in the yellow range is permissible for up to 5 minutes if required (e.g., go-around or take-off).  
  
If measures do not solve the problem, refer to 3.3.6 — DEFECTIVE RPM REGULATING SYSTEM.  
  
- [ ] **3.** Land at the nearest suitable airfield.  
⸻  
### 4B.2.2 Coolant Temperature  
  
**(a) High Coolant Temperature:**   
Proceed per Section 3.2.1 — ENGINE TEMPERATURE.  
  
**(b) Low Coolant Temperature:**  
- [ ] Check for COOL LVL / WATERLEV caution message.  
  
> **NOTE:** During extended descent from high altitudes with low power setting, coolant temperature may decrease. Increase power and decrease airspeed.  
  
**If COOL LVL / WATERLEV caution is displayed:**  
- [ ] Reduce power  
- [ ] Expect loss of coolant  
  
> **WARNING:** A further decrease in coolant temperature must be expected. Prepare for engine failure per 3.3.3 — ENGINE TROUBLESHOOTING IN FLIGHT.  

⸻  
### 4B.2.3 Oil Temperature  
  
**(a) High Oil Temperature:**   
Proceed per Section 3.2.2 — OIL TEMPERATURE.  
  
**(b) Low Oil Temperature:**  
  
> **NOTE:** During extended descent from high altitudes with low power setting, oil temperature may decrease. Increase power.  
  
- [ ] Increase power  
- [ ] Reduce airspeed  
⸻  
### 4B.2.4 Oil Pressure  
  
**High Oil Pressure:**  
- [ ] Check oil temperature.  
- [ ] Check coolant temperature.  
  
**If temperature is within the green range:**  
- [ ] Expect false oil pressure indication. Keep monitoring temperatures.  
  
**If temperature is outside the green range:**  
- [ ] Reduce power on engine.  
  
> **WARNING:** Land at the nearest suitable airfield. Prepare for engine failure per 3.7.1.   
> 
> **NOTE:** At low oil temperature, high oil pressure may occur. In this case reduce power setting until the warning disappears.  

⸻  
### 4B.2.5 Gearbox Temperature  
  
**High Gearbox Temperature:**   
Proceed per Section 3.2.4 — GEARBOX TEMPERATURE.  
  
> **NOTE:** There is no time limit associated with operating in the cautionary gearbox temperature range, but monitor temperature closely.  

⸻  
### 4B.2.6 Fuel Temperature  
  
**(a) High Fuel Temperature:**   
Proceed per Section 3.2.5 — L/R FUEL TEMPERATURE.  
  
**(b) Low Fuel Temperature:**  
- [ ] Increase power  
- [ ] Reduce airspeed  
  
> **CAUTION:** If temperature does not return to green range, perform a precautionary landing. Prepare for engine failure per 3.3.4.  

⸻  
### 4B.2.7 Voltage  
  
**(a) Low Voltage on the Ground with Engine Running:**  
- [ ] Terminate flight preparation.  
  
**(b) Low Voltage During Flight:**  
- [ ] **1.** Circuit breakers — check  
- [ ] **2.** Electrical equipment — OFF if not needed  
  
**If low voltage condition still exists:**  
- [ ] Follow procedure per Section 3.2.8 — ALTERNATOR FAIL.  
⸻  
### 4B.2.8 Current  
  
- [ ] **1.** Electrical equipment — switch OFF as necessary to reduce electric load  
  
**If problem does not clear:**  
  
- [ ] **2.** Land on nearest suitable airfield.  
⸻  
## 4B.3 Caution-Alerts  
  
### 4B.3.1 ECU A Failure  
  
### (a) ECU A Caution on the Ground  
  
- [ ] **1.** ALTERNATE AIR — check CLOSED  
- [ ] **2.** Fuel pump — OFF  
- [ ] **3.** VOTER switch — check AUTO  
- [ ] **4.** ECU B caution — check OFF  
- [ ] **5.** VOTER switch — ECU A  
- [ ] **6.** Wait — 5 seconds  
- [ ] **7.** VOTER switch — AUTO  
  
**If ECU A caution persists:** Terminate flight preparation.  
  
### (b) ECU A Caution During Flight  
  
> **NOTE:** System automatically switches to ECU B upon ECU A failure.  
  
- [ ] **1.** ALTERNATE AIR — OPEN  
- [ ] **2.** Fuel pump — ON  
- [ ] **3.** Circuit breakers — check / reset if necessary  
- [ ] **4.** VOTER switch — AUTO  
  
**If ECU A caution persists:** Land at the next suitable airfield. After landing, use (a) above as ECU caution clearing procedure.  
  
> **NOTE:** If additional engine problems are observed, refer to 3.3.3 — ENGINE TROUBLESHOOTING IN FLIGHT.  

⸻  
### 4B.3.2 ECU B Failure  
  
### (a) ECU B Caution on the Ground  
  
- [ ] **1.** ALTERNATE AIR — check CLOSED  
- [ ] **2.** Fuel Pump — OFF  
- [ ] **3.** VOTER switch — check AUTO  
- [ ] **4.** ECU A caution — check OFF  
- [ ] **5.** VOTER switch — ECU B  
- [ ] **6.** Wait — 5 seconds  
- [ ] **7.** VOTER switch — AUTO  
  
**If ECU B caution persists:** Terminate flight preparation.  
  
### (b) ECU B Caution During Flight  
  
> **NOTE:** System automatically switches to ECU A upon ECU B failure.  
  
- [ ] **1.** ALTERNATE AIR — OPEN  
- [ ] **2.** Fuel pump — ON  
- [ ] **3.** Circuit breakers — check / reset if necessary  
- [ ] **4.** VOTER switch — AUTO  
  
**If ECU B caution persists:** Land at the next suitable airfield. After landing, use (a) above as ECU caution clearing procedure.  
  
> **NOTE:** If additional engine problems are observed, refer to 3.3.3 — ENGINE TROUBLESHOOTING IN FLIGHT.  

⸻  
### 4B.3.3 Fuel Quantity Low  
  
- [ ] **1.** Fuel transfer pump — ON  
- [ ] **2.** Fuel quantity — check  
  
**If FUEL LOW caution is caused by un-coordinated flight:**  
  
> **CAUTION:** Prolonged un-coordinated flight can cause fuel starvation resulting in loss of power.  
  
- [ ] **3.** Return to coordinated flight (not more than approx. half a ball sideslip, 3°–5° bank)  
  
**If caution does not extinguish:**  
- [ ] Expect loss of fuel.  
- [ ] **4.** Fuel valve — EMERGENCY  
- [ ] **5.** Fuel transfer pump — OFF  
  
**If caution still does not extinguish:**  
- [ ] Be prepared for emergency landing. Proceed per 3.7.1 — EMERGENCY LANDING WITH ENGINE OFF.  
  
> **WARNING:** If air enters the high pressure fuel pump (e.g., empty fuel tank), inspection of the pump is necessary prior to next flight.  

⸻  
### 4B.3.4 Coolant Level  
  
Engine coolant level is low.  
  
- [ ] **1.** Annunciations / engine instruments — monitor  
  
Refer to Section 4B.2.2 — COOLANT TEMPERATURE.  
  
> **NOTE:** The indication is calibrated for straight and level flight. The caution message may be triggered during turns flown with slip, or while taxiing in curves.  

⸻  
### 4B.3.5 Pitot Heating Failure  
  
**If in icing conditions:**  
  
- [ ] **1.** Expect loss of airspeed indication.  
- [ ] **2.** Leave icing zone / refer to Section 3.9.1 — ICING.  
⸻  
### 4B.3.6 Engine Caution (if White Wire Annunciator Panel is installed)  
  
- [ ] **1.** Engine indications — check  
- [ ] **2.** Acknowledge button — press  
  
> **NOTE:** If an indication is outside of the green range, proceed per 4B.2 — INSTRUMENT INDICATIONS OUTSIDE OF THE GREEN RANGE.  

⸻  
## 4B.4 Canopy in Cooling Gap Position  
  
> **CAUTION:** If take-off was inadvertently done with the canopy in the cooling gap position, do not attempt to close the canopy in flight. Land the airplane and close the canopy on the ground.  

⸻  
## 4B.5 Failures in Flap Operating System  
  
- [ ] **1.** FLAPS position — check visually  
- [ ] **2.** Airspeed — keep in white range (max. 98 KIAS)  
- [ ] **3.** FLAPS switch — re-check all positions  
  
**Modified approach depending on available flap setting:**  
  
### (a) Only UP Available:  
  
Airspeed:  

| 940 kg (2072 lb) | 1000 kg (2205 lb) | 1100 kg (2425 lb) | 1200 kg (2646 lb) | 1216 kg (2681 lb) | 1280 kg (2822 lb) and above |
| ---------------- | ----------------- | ----------------- | ----------------- | ----------------- | --------------------------- |
| 71 KIAS | 73 KIAS | 78 KIAS | 82 KIAS | 82 KIAS | 83 KIAS |
  
  
Land at a flat approach angle; use POWER lever to control airplane speed and rate of descent.  
  
### (b) Only T/O Available:  
  
Airspeed:  

| 940 kg (2072 lb) | 1000 kg (2205 lb) | 1100 kg (2425 lb) | 1200 kg (2646 lb) | 1216 kg (2681 lb) | 1280 kg (2822 lb) and above |
| ---------------- | ----------------- | ----------------- | ----------------- | ----------------- | --------------------------- |
| 68 KIAS | 70 KIAS | 74 KIAS | 77 KIAS | 77 KIAS | 78 KIAS |
  
  
Land at a flat approach angle; use POWER lever to control airplane speed and rate of descent.  
  
### (c) Only LDG Available:  
Perform normal landing.  
⸻  
## 4B.6 Lightning Strike  
  
- [ ] **1.** Airspeed — as low as practicable, do not exceed vO (refer to Section 2.2)  
- [ ] **2.** Grasp airplane controls firmly  
- [ ] **3.** Autopilot (if installed) — disengage (check)  
- [ ] **4.** PFD (if G1000) / backup instruments — verify periodically  
- [ ] **5.** Continue flight below vO (refer to Section 2.2)  
- [ ] **6.** Land on the next suitable airfield  
  
> **CAUTION:** Due to possible damage, avoid abrupt or full control surface movements; avoid high g-loads on the airframe; avoid high yaw angles; avoid turbulent air; do not fly into areas of known or forecast icing.  

⸻  
## 4B.7 Landing with Mass Above Maximum Landing Mass  
  
Perform landing approach and landing per Chapter 4A, but maintain an increased airspeed during final landing approach.  
  
- [ ] Approach speed — 77 KIAS for a mass above 1280 kg (2822 lb), flaps LDG  
⸻  
## 4B.8 Starting Engine with External Power  
  
### 4B.8.1 Before Starting Engine  
  
- [ ] **1.** Pre-flight inspection — complete  
- [ ] **2.** Rudder pedals — adjusted and locked  
- [ ] **3.** Passengers — instructed  
- [ ] **4.** Safety harnesses — all fastened  
- [ ] **5.** Rear door — closed and locked  
- [ ] **6.** Door lock (if installed) — unlocked, key removed  
- [ ] **7.** Front canopy — Position 1 or 2 ("cooling gap")  
- [ ] **8.** Canopy lock (if installed) — unlocked, key removed  
- [ ] **9.** Parking brake — set  
- [ ] **10.** Flight controls — free movement  
- [ ] **11.** Trim wheel — T/O  
- [ ] **12.** POWER lever — check IDLE  
- [ ] **13.** Friction device on POWER lever — adjusted  
- [ ] **14.** Alternate air — check CLOSED  
- [ ] **15.** Alternate static valve — check CLOSED  
- [ ] **16.** VOTER switch — check AUTO  
- [ ] **17.** Fuel pumps — check OFF  
- [ ] **18.** ELECTRIC MASTER — check OFF  
- [ ] **19.** AVIONIC MASTER — check OFF  
- [ ] **20.** External power — connect  
- [ ] **21.** ELECTRIC MASTER — ON  
- [ ] **22.** G1000 (if installed) — wait until power-up completed; press ENT on MFD to acknowledge  
- [ ] **23.** White Wire annunciator panel (if installed) — check and press acknowledge button  
- [ ] **24.** COOL LVL caution (G1000) or WATERLEV caution (SED) — check OFF  
- [ ] **25.** Fuel temperature — check  
  
> **WARNING:** Never rotate the propeller by hand.  

⸻  
### 4B.8.2 Starting Engine (with External Power)  
  
> **CAUTION:** Do not operate the engine starter motor for more than 10 seconds.   
> 
> **WARNING:** If oil pressure has not moved from the red range within 3 seconds after starting, set ENGINE MASTER to OFF and investigate.  
  
- [ ] **1.** Strobe lights (ACL) — ON  
- [ ] **2.** ENGINE MASTER — ON  
- [ ] **3.** Annunciations / GLOW ON (G1000) or GLOW (White Wire) — check ON  
- [ ] **4.** Annunciations / engine indications — check  
  
> **WARNING:** Before starting, ensure propeller area is free and no persons can be endangered.  
  
**After GLOW indication is extinguished:**  
  
- [ ] **5.** START KEY — START as required / release when engine has started  
- [ ] **6.** Annunciations / engine indications — check OK/normal range  
- [ ] **7.** Annunciations / STARTER (G1000) or START (White Wire) — check OFF  
- [ ] **8.** Annunciations / Oil pressure — check OK  
- [ ] **9.** Circuit breakers — check all IN  
- [ ] **10.** Idle RPM — check, 710 ±30 RPM (above 7,000 ft pressure altitude idle RPM might be higher)  
- [ ] **11.** External power — disconnect  
- [ ] **12.** External power unit — check disconnected and moved clear of the airplane  
⸻  
*Document prepared from DA 40 NG Airplane Flight Manual, Rev. 3, 01-Jul-2014 (Doc. # 6.01.15-E)*  
